### PR TITLE
Autobuild Action

### PR DESCRIPTION
**Pull request by bblakely-dwolla**
Add Scheduled/Manual Build Trigger Action

### CODE REVIEW

**Comment by bpholt** [comment]
I think the [only things in this nucleus image are the Jenkins agent pieces](https://github.com/Dwolla/jenkins-agent-docker-nucleus/blob/3bc155b6a5d97ec3c5b621d2c0ec287c0a2b2696/Dockerfile#L19-L23). The alpine portion is only there to provide a system to facilitate [downloading and setting permissions on the files that remain](https://github.com/Dwolla/jenkins-agent-docker-nucleus/blob/3bc155b6a5d97ec3c5b621d2c0ec287c0a2b2696/Dockerfile#L9-L17). I'm not sure rebuilding this periodically will do anything since the Jenkins agent version is pinned.

**Comment by bblakely-dwolla** [comment]
The core sub-image doesn't pull in alpine directly, only transitively through here. The latest build of core (this morning) was 6 versions behind on Alpine, so I think this is needed here, unless I'm missing something with the core image.

**Comment by bpholt** [comment]
The [core image gets alpine from `openjdk:8-jre-alpine`](https://github.com/Dwolla/jenkins-agent-docker-core/blob/03a75eed45581f9a1b93b3d62020dda3c073a24f/alpine/Dockerfile#L2), which unfortunately we don't have direct control over.

We've been talking about switching to the AdoptOpenJDK images though. Those are better supported in general, and are what we're already using for our application images (as opposed to these Jenkins agent images).

**Comment by bblakely-dwolla** [comment]
Got it. I thought that might be the case, but was unable to find that on Dockerhub. Given this - I don't think we can build any recent Python code at this time. Is switching our JDK a relatively unimpactful change, or is that a major project?

**Comment by bpholt** [comment]
Switching JDK implementations should be pretty minor, since we'd plan to stay on the same major Java version and we're already using it successfully elsewhere, but it would behoove us to at least do some smoke testing.

**Pull request closed without merging**
